apiVersion: v1
kind: Service
metadata:
  name: sample-spring-kotlin-microservice
spec:
  type: ClusterIP
  selector:
    app: sample-spring-kotlin-microservice
  ports:
  - port: 8080
    targetPort: 8080
